apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  # n8n configuration
  N8N_PORT: "5678"
  N8N_HOST: "0.0.0.0"
  N8N_PROTOCOL: "https"
  WEBHOOK_URL: "https://n8n.paulbonneville.com"
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "admin"
  EXECUTIONS_MODE: "regular"
  
  # Database configuration (Google Cloud SQL)
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "35.225.58.181"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_USER: "postgres"
  DB_POSTGRESDB_SSL_ENABLED: "false"
  
  # Email configuration (AWS SES)
  N8N_EMAIL_MODE: "smtp"
  N8N_SMTP_HOST: "email-smtp.us-west-2.amazonaws.com"  # Change to your SES region
  N8N_SMTP_PORT: "587"
  N8N_SMTP_SSL: "true"
  N8N_DEFAULT_EMAIL: "paul@paulbonneville.com"  # Verified email address